protected/controllers/OrganizationsController.php
<?php

class OrganizationsController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view', 'tags'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Organization;

		if (isset($_GET['location']))
		{
			$model->location_id = $_GET['location'];
		}

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Organization']))
		{
			$model->attributes=$_POST['Organization'];
			if($model->save())
			{
				$this->redirect(array('view','id'=>$model->id));
				AutoCompleteHelper::overwriteJs('organizations'); //TODO: remove manual refresh when time compare bug is fixed
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Organization']))
		{
			$tagsUpdated = $model->tags != $_POST['Organization']['tags'];
			$model->attributes=$_POST['Organization'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
			if ($tagsUpdated) TagHelper::overwriteJs('organizations', true);
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Organization');
		TagHelper::addCriteria($dataProvider);
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	public function actionTags()
	{
		$this->breadcrumbs=array('Organizations'=>array('index'),'Tags');
		$this->renderText(TagHelper::links('organizations'));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Organization('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Organization']))
			$model->attributes=$_GET['Organization'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Organization the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Organization::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Organization $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='organization-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/controllers/PeopleController.php
<?php

class PeopleController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view', 'tags'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$model = $this->loadModel($id);

		$newStay = new Stay;
		$newStay->person_id = $id;

		$newInteraction = new Interaction;
		$newInteraction->person_id = $id;

		$this->render('view',array(
			'model'=>$model,
			'stays'=>$model->getStays(),
			'newStay'=>$newStay,
			'interactions'=>$model->getInteractions(),
			'newInteraction'=>$newInteraction,
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Person;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Person']))
		{
			$model->attributes=$_POST['Person'];
			$pwd = $model->generatePassword();
			if($model->save())
			{
				AppMails::send('welcome', $model, array('password'=>$pwd));
				$this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id = false)
	{
		if (!Yii::app()->user->isGuest && $id == false) $id = UserIdentity::context('id');
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Person']))
		{
			$tagsUpdated = $model->tags != $_POST['Person']['tags'];
			$model->attributes=$_POST['Person'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
			if ($tagsUpdated) TagHelper::overwriteJs('people', true);
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Person');
		TagHelper::addCriteria($dataProvider);
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	public function actionTags()
	{
		$this->breadcrumbs=array('People'=>array('index'),'Tags');
		$this->renderText(TagHelper::links('people'));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Person('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Person']))
			$model->attributes=$_GET['Person'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Person the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Person::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Person $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='person-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex()
	{
		$stats = $this->getCount('people') . '<br />' . $this->getCount('organizations') . '<br />' . $this->getCount('locations');

		$this->render('index',array('stats'=>$stats));
	}

	private function getCount($tbl)
	{
		$cnt = Yii::app()->db->createCommand('select count(*) from '.$tbl.'')->queryScalar();
		$base = Yii::app()->baseUrl;
		$fmt = '<a href="%s/%s/">%s %s</a>';
		return sprintf($fmt, $base, $tbl, $cnt, ucfirst($tbl));
	}

	public function actionSearch()
	{
		if (!isset($_GET['s']))
		{
			$this->renderText('A search query is necessary, please use the search box in the menu bar');
			return;
		}

		$s = $_GET['s'];
		$people = Person::model()->findAllBySql("select * from people where name like '%$s%' or about like '%$s%' or tags like '%$s%'");
		$orgs = Organization::model()->findAllBySql("select * from organizations where name like '%$s%' or about like '%$s%' or tags like '%$s%'");
		$this->render('search',array('people'=>$people,'organizations'=>$orgs));
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
	    if($error=Yii::app()->errorHandler->error)
	    {
	    	if(Yii::app()->request->isAjaxRequest)
	    		echo $error['message'];
	    	else
	        	$this->render('error', $error);
	    }
	}

	/**
	 * Displays the contact page
	 */
	public function actionContact()
	{
		$model=new ContactForm;
		if(isset($_POST['ContactForm']))
		{
			$model->attributes=$_POST['ContactForm'];
			if($model->validate())
			{
				$headers="From: {$model->email}\r\nReply-To: {$model->email}";
				mail(Yii::app()->params['adminEmail'],$model->subject,$model->body,$headers);
				Yii::app()->user->setFlash('contact','Thank you for contacting us. We will respond to you as soon as possible.');
				$this->refresh();
			}
		}
		$this->render('contact',array('model'=>$model));
	}

	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$model=new LoginForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login())
				$this->redirect(Yii::app()->user->returnUrl);
		}
		else
		{
			$model->rememberMe = true;
		}
		// display the login form
		$this->render('login',array('model'=>$model));
	}

	public function actionReset()
	{
		if (isset($_GET['token']))
		{
			$mode = 'password';
			$person = Person::getByToken($_GET['token']);
			$model = new LoginForm;
			$model->username = $person->email;
			if (isset($_POST['LoginForm']))
			{
				$password = $_POST['LoginForm']['password'];
				$person->password = md5($password);
				if (!$person->save())
					die(CHtml::errorSummary($person));

				AppMails::send('reset-password-done', $person, array('password'=>$password));
				$this->redirect('/site/login');
			}
		}
		else
		{
			$mode = 'username';
			$model = new LoginForm;
			if (isset($_POST['LoginForm']))
			{
				$email = $_POST['LoginForm']['username'];
				$model->username = $email;
				$person = Person::model()->findByAttributes(array('email'=>$email));
				if ($person == null) {
					$model->addError('username', 'Email not found');
				} else {
					AppMails::send('reset-password', $person);
					$this->renderText('An email has been sent to ' . $email);
					return;
				}
			}
		}

		$this->render('login',array('model'=>$model, 'mode'=>$mode));
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}
}

protected/views/layouts/column1.php
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />

	<!-- blueprint CSS framework -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/site.css" />

	<link rel="shortcut icon" href="<?php echo Yii::app()->request->baseUrl; ?>/favicon.ico" />;

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>

<div class="container" id="page">

	<div id="header">
		<div id="logo"><?php echo Yii::app()->name . '<small>, ' . Yii::app()->params['byline'] . '</small>'; ?></div>
	</div><!-- header -->

	<div id="mainMbMenu" class="nav popout">
		<form action="<?php echo Yii::app()->baseUrl; ?>/site/search" style="float: right; margin: 3px 20px 0 0;">
			<input type="text" name="s" placeholder="search" value="<?php echo isset($_GET['s']) ? $_GET['s'] : ''; ?>" />
		</form>
		<?php $this->widget('application.extensions.mbmenu.MbMenu',array(
			'items'=>array(
				array('label'=>'Home', 'url'=>Yii::app()->baseUrl, 'items' => array(
					array('label'=>'About', 'url'=>array('/site/page', 'view'=>'about')),
					array('label'=>'Register', 'url'=>array('/site/page', 'view'=>'register')),
					array('label'=>'Terms', 'url'=>array('/site/page', 'view'=>'terms')),
					array('label'=>'Contact', 'url'=>array('/site/contact/')),
				)),
				array('label'=>'Administer', 'visible'=>AppEnv::get('gii', 'CodeGen', 0), 'items'=> array(
					array('label'=>'Generator', 'url'=>array('/gii'), 'visible' => AppEnv::get('gii', 'CodeGen', 0), 'linkOptions' => array('target' => 'new')),
					//array('label'=>'Site', 'url'=>array('/site/page', 'view'=>'admin')),
				)),
				array('label'=>'People', 'url'=>array('/people/'), 'items'=> array(
					array('label'=>'Tags', 'url'=>array('/people/tags')),
				)),
				array('label'=>'Organizations', 'url'=>array('/organizations/'), 'items'=> array(
					array('label'=>'Tags', 'url'=>array('/organizations/tags')),
				)),
				array('label'=>'Locations', 'url'=>array('/locations/')),
				array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest, 'items' => array(
					array('label'=>'Reset Password', 'url'=>array('/site/reset')),
				)),
				array('label'=>'Logout ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest, 'items' => array(
					array('label'=>'Update Profile', 'url'=>array('/people/update')),
				)),
			),
		)); ?>
	</div><!-- mainmenu -->
	<?php if(isset($this->breadcrumbs)):?>
		<?php $this->widget('zii.widgets.CBreadcrumbs', array(
			'links'=>$this->breadcrumbs,
		)); ?><!-- breadcrumbs -->
	<?php endif?>

	<?php echo $content; ?>

	<div class="clear"></div>

	<div id="footer">
		<span style="float: right;">Powered by <a href="http://www.yiiframework.com/" target="_blank">Yii Framework</a>,
			built by <a href="http://tg.cselian.com" target="_blank">cselian</a>.</span>
		Copyright &copy; <?php echo date('Y'); ?> <?php echo CHtml::link('Team Sixty Five Plus', array('/site/page', 'view' => 'about')); ?>.
		You agree to our <?php echo CHtml::link('Terms', array('/site/page', 'view' => 'terms')); ?>.
		
	</div><!-- footer -->
</div><!-- page -->

</body>
</html>