protected/controllers/InteractionsController.php
<?php

class InteractionsController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Interaction;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Interaction']))
		{
			$model->attributes=$_POST['Interaction'];
			if($model->save()) {
				$red = array('update','id'=>$model->id);
				if ($model->orgCreated) $red['orgCreated'] = '1';
				$this->redirect($red);
			} else {
				die(CHtml::errorSummary($model));
			}
		}
		else
		{
			die('direct access not allowed');
		}
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Interaction']))
		{
			$model->attributes=$_POST['Interaction'];
			if($model->save())
				die('<script>window.close();</script>');
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Interaction the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Interaction::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Interaction $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='interaction-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/interactions/_form.php
<?php
/* @var $this InteractionsController */
/* @var $model Interaction */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'interaction-form',
	'action'=> $model->isNewRecord ? Yii::app()->baseUrl . '/interactions/create' : '',
	'htmlOptions' => array('target'=> $model->isNewRecord ? '_blank' : ''),
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>

	<?php echo $form->errorSummary($model); ?>

	<?php if (!$model->isNewRecord) { ?><div class="row">
		<?php echo $form->labelEx($model,'person_id'); ?>
		<?php echo $form->textField($model,'person_id'); ?>
		<?php echo $model->person_id != '' ? $model->person->link() : ''; ?>
		<?php echo $form->error($model,'person_id'); ?>
	</div><?php } else { echo $form->hiddenField($model,'person_id'); } ?>

	<div class="row">
		<?php echo $form->labelEx($model,'organization_id'); ?>
		<?php echo $form->textField($model,'organization_id'); ?>
		<?php echo $model->organization_id != '' ? $model->organization->link() : '<a target="_blank"></a>'; ?>
		<?php AutoCompleteHelper::registerJs('organizations', 'Interaction_organization_id') ?>
		<?php if (isset($_GET['orgCreated'])) echo '(Organization with type ' 
			. $model->organization->type . ' just created - '
			. CHtml::link('edit', array('organizations/update/' . $model->organization->id), array('target'=>'_blank')) . ')'; ?>
		<?php echo $form->error($model,'organization_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'type'); ?>
		<?php echo $form->radioButtonList($model,'type', Interaction::$types, array('separator' => '')); ?>
		<?php echo $form->error($model,'type'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'from'); ?>
		<?php echo Formatter::datePicker($this, $model,'from'); ?>
		<?php echo $form->error($model,'from'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'to'); ?>
		<?php echo Formatter::datePicker($this, $model,'to'); ?>
		<?php echo $form->error($model,'to'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'on'); ?>
		<?php echo Formatter::datePicker($this, $model,'on'); ?>
		<?php echo $form->error($model,'on'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'notes'); ?>
		<?php echo $form->textField($model,'notes',array('size'=>60,'maxlength'=>256)); ?>
		<?php echo $form->error($model,'notes'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/interactions/_view.php
<?php
/* @var $this InteractionsController */
/* @var $data Interaction */
?>

	<?php if (UserIdentity::context('admin'))
		echo CHtml::link('...' , array('/interactions/update', 'id'=>$data->id), array('class' => 'right', 'target' => '_blank')); ?>

	<?php echo $data->type(); ?>
	in <?php echo $data->organization->link(); ?>

	<?php $data->txnDate('from'); ?>
	<?php $data->txnDate('to'); ?>
	<?php $data->txnDate('on', true); ?>

	<b><?php echo CHtml::encode($data->getAttributeLabel('notes')); ?>:</b>
	<?php echo CHtml::encode($data->notes); ?>
	<br />

protected/views/interactions/update.php
<?php
/* @var $this InteractionsController */
/* @var $model Interaction */

$this->breadcrumbs=array(
	'Interactions'=>array('index'),
	$model->id=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Interaction', 'url'=>array('index')),
	array('label'=>'Create Interaction', 'url'=>array('create')),
	array('label'=>'View Interaction', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage Interaction', 'url'=>array('admin')),
);
?>

<h1>Update Interaction <?php echo $model->id; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>